#!/bin/bash

# Get the host user information (UID, GID, and username)
HOST_USERNAME=$(id -un)
HOST_UID=$(id -u)
HOST_GID=$(id -g)
HOST_DOCKER_GID=$(getent group docker | cut -d: -f3)

# This is a very stupid workaround, but there doesn't seem to be a better way to set build arguments from vscode.
ENV_FILE=".env"
ENV_DIR=".devcontainer/container"
ENV_PATH="$ENV_DIR/$ENV_FILE"



echo "Extracting host information..."
echo "Host User Information:"
echo "Host User: $HOST_USERNAME"
echo "Host UID: $HOST_UID"
echo "Host GID: $HOST_GID"
echo "Host Docker GID: $HOST_DOCKER_GID"
echo "Host User Information extracted successfully."
echo "Setting up environment variables..."

# Create the directory if it doesn't exist
mkdir -p ${ENV_DIR}

echo "# This file is auto-generated by the extract-env.sh script" > ${ENV_PATH}
echo "HOST_USERNAME=$HOST_USERNAME" >> ${ENV_PATH}
echo "HOST_UID=$HOST_UID" >> ${ENV_PATH}
echo "HOST_GID=$HOST_GID" >> ${ENV_PATH}
echo "HOST_DOCKER_GID=$HOST_DOCKER_GID" >> ${ENV_PATH}


echo "Environment variables set up successfully."
